/**
 * PR Comment service for managing comments on pull requests
 */

import * as core from '@actions/core'
import * as github from '@actions/github'
import { AcrolinxAnalysisResult, AnalysisOptions } from '../types/index.js'
import { getQualityEmoji, calculateScoreSummary } from '../utils/score-utils.js'
import { handleGitHubError, logError } from '../utils/error-utils.js'

/**
 * Interface for PR comment data
 */
export interface PRCommentData {
  owner: string
  repo: string
  prNumber: number
  results: AcrolinxAnalysisResult[]
  config: AnalysisOptions
}

/**
 * Generate markdown table for analysis results
 */
function generateResultsTable(results: AcrolinxAnalysisResult[]): string {
  if (results.length === 0) {
    return 'No files were analyzed.'
  }

  const tableHeader = `| File | Quality | Clarity | Grammar | Style Guide | Tone | Terminology |
|------|---------|---------|---------|-------------|------|-------------|`

  const tableRows = results
    .map((result) => {
      const { filePath, result: scores } = result
      const qualityEmoji = getQualityEmoji(scores.quality.score)

      return `| ${filePath} | ${qualityEmoji} ${scores.quality.score} | ${scores.clarity.score} | ${scores.grammar.score} | ${scores.style_guide.score} | ${scores.tone.score} | ${scores.terminology.score} |`
    })
    .join('\n')

  return `${tableHeader}\n${tableRows}`
}

/**
 * Generate summary section
 */
function generateSummary(results: AcrolinxAnalysisResult[]): string {
  if (results.length === 0) {
    return ''
  }

  const summary = calculateScoreSummary(results)
  const overallQualityEmoji = getQualityEmoji(summary.averageQualityScore)

  return `
## 📊 Summary

**Overall Quality Score:** ${overallQualityEmoji} ${summary.averageQualityScore}

| Metric | Average Score |
|--------|---------------|
| Quality | ${summary.averageQualityScore} |
| Clarity | ${summary.averageClarityScore} |
| Grammar | ${summary.averageGrammarScore} |
| Style Guide | ${summary.averageStyleGuideScore} |
| Tone | ${summary.averageToneScore} |
| Terminology | ${summary.averageTerminologyScore} |

**Files Analyzed:** ${summary.totalFiles}
`
}

/**
 * Generate complete comment body
 */
function generateCommentBody(
  results: AcrolinxAnalysisResult[],
  config: AnalysisOptions
): string {
  const header = `## 🔍 Acrolinx Analysis Results

This comment was automatically generated by the Acrolinx Analyzer GitHub Action.`

  const table = generateResultsTable(results)
  const summary = generateSummary(results)

  return `${header}

${table}

${summary}

---
*Analysis performed on ${new Date().toLocaleString()}*
*Quality Score Legend: 🟢 80+ | 🟡 60-79 | 🔴 0-59*
*Configuration: Dialect: ${config.dialect} | Tone: ${config.tone} | Style Guide: ${config.styleGuide}*`
}

/**
 * Find existing Acrolinx comment on PR
 */
async function findExistingAcrolinxComment(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number
): Promise<number | null> {
  try {
    const response = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: prNumber
    })

    const acrolinxComment = response.data.find((comment) =>
      comment.body?.includes('## 🔍 Acrolinx Analysis Results')
    )

    return acrolinxComment?.id || null
  } catch (error) {
    core.warning(`Failed to find existing Acrolinx comment: ${error}`)
    return null
  }
}

/**
 * Create or update PR comment with analysis results
 */
export async function createOrUpdatePRComment(
  octokit: ReturnType<typeof github.getOctokit>,
  commentData: PRCommentData
): Promise<void> {
  const { owner, repo, prNumber, results, config } = commentData

  try {
    // Check if we have permission to comment on PRs
    try {
      await octokit.rest.repos.get({
        owner,
        repo
      })
    } catch (error: unknown) {
      const githubError = error as { status?: number }
      if (githubError.status === 403) {
        core.error(
          '❌ Permission denied: Cannot access repository. Make sure the GitHub token has "pull-requests: write" permission.'
        )
        return
      }
      throw error
    }

    const commentBody = generateCommentBody(results, config)
    const existingCommentId = await findExistingAcrolinxComment(
      octokit,
      owner,
      repo,
      prNumber
    )

    if (existingCommentId) {
      // Update existing comment
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existingCommentId,
        body: commentBody
      })
      core.info(`✅ Updated existing Acrolinx comment on PR #${prNumber}`)
    } else {
      // Create new comment
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: prNumber,
        body: commentBody
      })
      core.info(`✅ Created new Acrolinx comment on PR #${prNumber}`)
    }
  } catch (error: unknown) {
    const githubError = handleGitHubError(error, 'Create/update PR comment')

    if (githubError.status === 403) {
      core.error(
        '❌ Permission denied: Cannot create or update comments on pull requests.'
      )
      core.error(
        'Please ensure the GitHub token has "pull-requests: write" permission.'
      )
    } else if (githubError.status === 404) {
      core.error(
        '❌ Pull request not found. Make sure the PR exists and is accessible.'
      )
    } else {
      logError(githubError, 'Failed to create/update PR comment')
    }
  }
}

/**
 * Check if current event is a pull request
 */
export function isPullRequestEvent(): boolean {
  return github.context.eventName === 'pull_request'
}

/**
 * Get PR number from context
 */
export function getPRNumber(): number | null {
  if (github.context.eventName === 'pull_request') {
    return github.context.issue.number
  }
  return null
}
