/**
 * Tests for Job Summary Service
 */

import { jest } from '@jest/globals'
import * as core from '../__fixtures__/core.js'

// Spy on core methods
const infoSpy = jest.spyOn(core, 'info')
const errorSpy = jest.spyOn(core, 'error')

// Create mock summary object
const mockSummary = {
  addHeading: jest.fn().mockReturnThis(),
  addRaw: jest.fn().mockReturnThis(),
  write: jest.fn().mockResolvedValue(undefined)
}

// Mock @actions/core
jest.unstable_mockModule('@actions/core', () => ({
  ...core,
  summary: mockSummary
}))

// Import the module after mocking
let jobSummaryService: typeof import('../src/services/job-summary-service.js')

beforeAll(async () => {
  jobSummaryService = await import('../src/services/job-summary-service.js')
})

describe('Job Summary Service', () => {
  beforeEach(() => {
    jest.clearAllMocks()
    infoSpy.mockClear()
    errorSpy.mockClear()
  })

  const mockResults = [
    {
      filePath: 'test.md',
      result: {
        quality: { score: 85 },
        clarity: { score: 78 },
        grammar: { score: 90, issues: 2 },
        style_guide: { score: 88, issues: 1 },
        tone: { score: 82 },
        terminology: { score: 95, issues: 0 }
      },
      timestamp: '2024-01-15T10:30:00Z'
    },
    {
      filePath: 'example.md',
      result: {
        quality: { score: 75 },
        clarity: { score: 72 },
        grammar: { score: 85, issues: 1 },
        style_guide: { score: 80, issues: 2 },
        tone: { score: 78 },
        terminology: { score: 88, issues: 1 }
      },
      timestamp: '2024-01-15T10:35:00Z'
    }
  ] as import('../src/types/index.js').AcrolinxAnalysisResult[]

  const mockConfig = {
    dialect: 'american_english',
    tone: 'formal',
    styleGuide: 'ap'
  }

  describe('createJobSummary', () => {
    it('should create job summary with results', async () => {
      await jobSummaryService.createJobSummary(
        mockResults,
        mockConfig,
        'workflow_dispatch'
      )

      expect(mockSummary.addRaw).toHaveBeenCalledWith(
        expect.stringContaining('# 🔍 Acrolinx Analysis Results')
      )
      expect(mockSummary.addRaw).toHaveBeenCalledWith(
        expect.stringContaining(
          'This summary was automatically generated by the Acrolinx Analyzer GitHub Action for **workflow_dispatch** event.'
        )
      )
      expect(mockSummary.addRaw).toHaveBeenCalledWith(
        expect.stringContaining(
          '| File | Quality | Clarity | Grammar | Style Guide | Tone | Terminology |'
        )
      )
      expect(mockSummary.addRaw).toHaveBeenCalledWith(
        expect.stringContaining('test.md')
      )
      expect(mockSummary.addRaw).toHaveBeenCalledWith(
        expect.stringContaining('example.md')
      )
      expect(mockSummary.addRaw).toHaveBeenCalledWith(
        expect.stringContaining('## 📊 Summary')
      )
      expect(mockSummary.write).toHaveBeenCalled()
      expect(infoSpy).toHaveBeenCalledWith(
        '✅ Job summary created successfully'
      )
    })

    it('should handle empty results', async () => {
      await jobSummaryService.createJobSummary([], mockConfig, 'schedule')

      expect(mockSummary.addHeading).toHaveBeenCalledWith(
        '🔍 Acrolinx Analysis Results'
      )
      expect(mockSummary.addRaw).toHaveBeenCalledWith('No files were analyzed.')
      expect(mockSummary.write).toHaveBeenCalled()
    })

    it('should handle errors gracefully', async () => {
      const error = new Error('Summary creation failed')
      mockSummary.write.mockRejectedValue(error)

      await jobSummaryService.createJobSummary(
        mockResults,
        mockConfig,
        'workflow_dispatch'
      )

      expect(errorSpy).toHaveBeenCalledWith(
        'Failed to create job summary: Error: Summary creation failed'
      )
    })

    it('should include configuration details', async () => {
      await jobSummaryService.createJobSummary(
        mockResults,
        mockConfig,
        'schedule'
      )

      expect(mockSummary.addRaw).toHaveBeenCalledWith(
        expect.stringContaining(
          '*Configuration: Dialect: american_english | Tone: formal | Style Guide: ap*'
        )
      )
    })

    it('should include quality score legend', async () => {
      await jobSummaryService.createJobSummary(
        mockResults,
        mockConfig,
        'workflow_dispatch'
      )

      expect(mockSummary.addRaw).toHaveBeenCalledWith(
        expect.stringContaining(
          '*Quality Score Legend: 🟢 80+ | 🟡 60-79 | 🔴 0-59*'
        )
      )
    })
  })
})
